Feat/support ro ph api
xendit/xendit-java pull request #102
Opened 2021-11-12 10:16 UTC by ingemar0720

[Jira ticket](https://xendit.atlassian.net/browse/PAYM-8154)
This ticket is to add RO PH API into Xendit Java SDK.
- add new API
- add unit-test

2021-11-16 02:50 UTC, xen-HendryZheng requested changes

2021-11-29 02:51 UTC, ingemar0720 commented on xendit-java-lib/src/main/java/com/xendit/model/RegionalRetailOutletPaymentCode.java
> +    PH
I remove the ALFAMART/INDOMARET for now as this RegionalRetailOutlet architecture is not ready for INDO merchant to use. We could add them back once the new service is ready.

2021-11-29 02:52 UTC, ingemar0720 commented on xendit-java-lib/src/main/java/com/xendit/model/RegionalRetailOutletPaymentCode.java
> +    PHP
Not ready to support INDO market for now. So I keep this and remove all Indo related enum like ALFAMART/INDOMARET.

2021-11-29 05:23 UTC, xen-HendryZheng approved these changes
LGTM

2021-11-29 05:23 UTC, merged